### ISSUE TITLE
Inconsistency error

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/biotrainer#55]
- I am using the secondary structure data: http://data.bioembeddings.com/public/FLIP/fasta/secondary_structure/
- I miss about `734` sequences in the embeddings file I generated
- I set `ignore_redundant_sequences` to True

```
$ biotrainer biotrainer.yml 
2022-11-02 11:48:55,920 INFO auto_resume is enabled in the configuration file, but no valid checkpoint was found. Training new model from scratch.
2022-11-02 11:48:55,920 INFO Using Seed: 42
2022-11-02 11:48:56,060 INFO Embeddings file was found at /raid/cdallago/experiments/20221101_bionemo/secstruct/embeddings_file.h5. Embeddings have not been computed.
2022-11-02 11:48:56,061 INFO Loading embeddings from: /raid/cdallago/experiments/20221101_bionemo/secstruct/embeddings_file.h5
2022-11-02 11:48:59,623 INFO Read 10706 entries.
2022-11-02 11:48:59,623 INFO Time elapsed for reading embeddings: 3.6[s]
2022-11-02 11:48:59,623 INFO Number of features: 768
2022-11-02 11:49:02,571 WARNING Found 734 label(s) without a corresponding entry in the embeddings file! Because ignore_redundant_sequences flag is set, these labels are dropped for training. Data loss: 0.06856%
Traceback (most recent call last):
  File "/home/cdallago/miniconda3/envs/python3.8/bin/biotrainer", line 5, in <module>
    main()
  File "/home/cdallago/git/biotrainer/biotrainer/utilities/cli.py", line 24, in main
    parse_config_file_and_execute_run(arguments.config_path[0])
  File "/home/cdallago/git/biotrainer/biotrainer/utilities/executer.py", line 71, in parse_config_file_and_execute_run
    out_config = training_and_evaluation_routine(output_dir=str(output_dir), log_dir=str(log_dir), **config)
  File "/home/cdallago/git/biotrainer/biotrainer/trainers/trainer.py", line 81, in training_and_evaluation_routine
    train_dataset, val_dataset, test_dataset = target_manager.get_datasets(id2emb)
  File "/home/cdallago/git/biotrainer/biotrainer/trainers/TargetManager.py", line 196, in get_datasets
    self._validate_targets(id2emb)
  File "/home/cdallago/git/biotrainer/biotrainer/trainers/TargetManager.py", line 173, in _validate_targets
    id2emb.pop(seq_id)  # Remove redundant labels
KeyError: '3ite-A'
```

**Comment by sacdallago** [comment]
For completeness, config looks like this:

```
sequence_file: sequences.fasta
labels_file: sampled.fasta
mask_file: resolved.fasta

#embedder_name: bionemo_esm1nv     
embeddings_file: embeddings_file.h5

protocol: residue_to_class
ignore_file_inconsistencies: True

model_choice: CNN
optimizer_choice: adam
loss_choice: cross_entropy_loss
num_epochs: 20
use_class_weights: False
learning_rate: 1e-3
batch_size: 128
```
