### ISSUE TITLE
Value Error when Early stopping was engaged

### ISSUE THREAD

**Issue by HenrikOtterstedt** [sacdallago/biotrainer#79]
Encountered Value Error when early stopping was engaged. 
Info: 

[bio_trainer_config.txt](https://github.com/sacdallago/biotrainer/files/11536913/bio_trainer_config.txt)

Error Message:
Traceback (most recent call last):
  File "/mnt/project/otterstedt/biotrainer/run-biotrainer.py", line 6, in <module>
    biotrainer_main(sys.argv[1:])
  File "/mnt/project/otterstedt/biotrainer/biotrainer/utilities/cli.py", line 38, in main
    parse_config_file_and_execute_run(config_path)
  File "/mnt/project/otterstedt/biotrainer/biotrainer/utilities/executer.py", line 126, in parse_config_file_and_execute_run
    out_config = trainer.training_and_evaluation_routine()
  File "/mnt/project/otterstedt/biotrainer/biotrainer/trainers/trainer.py", line 123, in training_and_evaluation_routine
    test_dataset_embeddings = self._create_embeddings_dataset(test_dataset, mode="test")
  File "/mnt/project/otterstedt/biotrainer/biotrainer/trainers/trainer.py", line 184, in _create_embeddings_dataset
    return get_dataset(self._protocol, split)
  File "/mnt/project/otterstedt/biotrainer/biotrainer/datasets/__init__.py", line 28, in get_dataset
    return dataset(samples=samples)
  File "/mnt/project/otterstedt/biotrainer/biotrainer/datasets/EmbeddingsDataset.py", line 10, in __init__
    self.ids, self.inputs, self.targets = zip(
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by SebieF** [comment]
Thank you for creating the issue :)

Do you have any samples in your test set? I get the same error when running the `residues_to_class` [example](https://github.com/sacdallago/biotrainer/blob/main/examples/residues_to_class/sequences.fasta) while removing the test sequences.
This is how the input file should look like:
```
>Seq1 TARGET=Glob SET=train
SEQWENCE
>Seq2 TARGET=GlobSP SET=train
SEQPRT
>Seq3 TARGET=GlobSP SET=val
PRTEIN
>Seq4 TARGET=TM SET=val
SEQVENCEPROTEI
>Seq5 TARGET=TMSP SET=test
PRTEINSEQWENCE
>Seq6 TARGET=Glob SET=test
PRTEINSEQPRT
```

**Comment by HenrikOtterstedt** [comment]
Yes that was exactly the problem in my case. Thanks for checking.
